version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy:v1.23.0
    container_name: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10000:10000"
      - "9901:9901"
    depends_on:
      - gin

  gin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
